<?php

namespace Database\Seeders;

use App\Models\TrainSet;
use Illuminate\Database\Seeder;

class TrainSetSeeder extends Seeder
{
    public function run(): void
    {
        $fourCarSets = ['T16', 'T17', 'T18', 'T19', 'T20', 'T21', 'T22', 'T23', 'T25'];
        $defaults = [
            'T01' => ['default_berth_no' => 'CT09B', 'default_outbound_run_no' => '1003', 'default_first_contact_plan' => '03:20', 'default_departure_plan_time' => '03:50', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '04:10', 'default_inbound_run_no' => '1176', 'default_end_station' => 'KTW4', 'default_end_time' => '23:54', 'default_end_no' => 'CT09B', 'default_end_depot' => 'TWP, CT09B', 'default_row_theme' => null],
            'T02' => ['default_berth_no' => 'DMG1', 'default_outbound_run_no' => '1004', 'default_first_contact_plan' => '03:20', 'default_departure_plan_time' => '03:50', 'default_ktw_platform' => '6', 'default_ktw_next_depart_time' => '04:10', 'default_inbound_run_no' => '1176', 'default_end_station' => 'KTW4', 'default_end_time' => '23:54', 'default_end_no' => 'CT07B', 'default_end_depot' => 'RST3', 'default_special_instructions' => '*** 4 Cars // inspection From DMG1 to RST3 / 1176 Last train NL RST3 to KTW4', 'default_row_theme' => null],
            'T03' => ['default_berth_no' => 'CT06B', 'default_outbound_run_no' => '1008', 'default_first_contact_plan' => '03:50', 'default_departure_plan_time' => '04:20', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '04:40', 'default_inbound_run_no' => '1146', 'default_end_station' => 'KTW4', 'default_end_time' => '20:14', 'default_end_no' => 'CT06B', 'default_end_depot' => 'TWP', 'default_row_theme' => 'pink'],
            'T04' => ['default_berth_no' => 'KTW3', 'default_outbound_run_no' => '1001', 'default_first_contact_plan' => '03:40', 'default_departure_plan_time' => '04:10', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '04:30', 'default_inbound_run_no' => '1179', 'default_end_station' => 'RST2', 'default_end_time' => '23:53', 'default_end_no' => 'CT08B', 'default_end_depot' => 'RST2', 'default_special_instructions' => 'inspection to DMG // 1179 Last train from KTW3 to RST2', 'default_row_theme' => null],
            'T05' => ['default_berth_no' => 'CT04B', 'default_outbound_run_no' => '1115', 'default_first_contact_plan' => '15:50', 'default_departure_plan_time' => '16:10', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '16:50', 'default_inbound_run_no' => '1150', 'default_end_station' => 'KTW4', 'default_end_time' => '20:39', 'default_end_no' => 'CT04B', 'default_end_depot' => 'RST2', 'default_special_instructions' => '(Peak time) 1150 Last train NL from KTW3 to RST2', 'default_row_theme' => 'red'],
            'T06' => ['default_berth_no' => 'CT06B', 'default_outbound_run_no' => '1008', 'default_first_contact_plan' => '03:50', 'default_departure_plan_time' => '04:20', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '04:40', 'default_inbound_run_no' => '1146', 'default_end_station' => 'KTW4', 'default_end_time' => '20:14', 'default_end_no' => 'CT06B', 'default_end_depot' => 'TLC1', 'default_special_instructions' => 'From Depot app WSN to RST3 non stop // evening peak 1146 Last train NL from RST3 to KTW4', 'default_row_theme' => 'pink'],
            'T07' => ['default_berth_no' => 'CT03B', 'default_outbound_run_no' => '1021', 'default_first_contact_plan' => '05:50', 'default_departure_plan_time' => '06:10', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '06:40', 'default_inbound_run_no' => '1056', 'default_end_station' => 'KTW4', 'default_end_time' => '10:24', 'default_end_no' => 'TWP, CT04B', 'default_end_depot' => 'Peak time', 'default_special_instructions' => '(Peak time) 1056 Last train NL', 'default_row_theme' => 'blue'],
            'T08' => ['default_berth_no' => 'CT11B', 'default_outbound_run_no' => '1301', 'default_first_contact_plan' => '04:00', 'default_departure_plan_time' => '04:30', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '04:50', 'default_inbound_run_no' => '1302', 'default_end_station' => 'KTW4', 'default_end_time' => '00:13', 'default_end_no' => 'CT11B', 'default_end_depot' => 'DMG1', 'default_special_instructions' => '1301 KTW3 Non Stop to DMG1 / Standby @ DMG1 / 1302 Non Stop to KTW4', 'default_row_theme' => 'green'],
            'T09' => ['default_berth_no' => 'CT04B', 'default_outbound_run_no' => '1115', 'default_first_contact_plan' => '15:50', 'default_departure_plan_time' => '16:10', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '16:50', 'default_inbound_run_no' => '1150', 'default_end_station' => 'KTW4', 'default_end_time' => '20:39', 'default_end_no' => 'CT04B', 'default_end_depot' => 'TWP', 'default_row_theme' => 'red'],
            'T10' => ['default_berth_no' => 'KTW9', 'default_outbound_run_no' => '2001', 'default_first_contact_plan' => '03:15', 'default_departure_plan_time' => '03:45', 'default_ktw_platform' => '9', 'default_ktw_next_depart_time' => '04:05', 'default_inbound_run_no' => 'SPARE WL', 'default_end_station' => 'KTW10', 'default_end_time' => '00:00', 'default_end_no' => 'CT12B', 'default_end_depot' => 'KTW10', 'default_special_instructions' => '*** 6 Cars // 2001 Inspection TWC / Standby KTW10', 'default_row_theme' => null],
            'T11' => ['default_berth_no' => 'CT02B', 'default_outbound_run_no' => '5011', 'default_first_contact_plan' => '04:00', 'default_departure_plan_time' => null, 'default_ktw_platform' => null, 'default_ktw_next_depart_time' => null, 'default_inbound_run_no' => null, 'default_end_station' => null, 'default_end_time' => '0:00', 'default_end_no' => 'CT02B', 'default_end_depot' => 'Standby 6 cars', 'default_row_theme' => 'yellow'],
            'T12' => ['default_berth_no' => 'KTW4', 'default_outbound_run_no' => '1007', 'default_first_contact_plan' => '03:45', 'default_departure_plan_time' => '04:15', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '05:00', 'default_inbound_run_no' => '1178', 'default_end_station' => 'KTW4', 'default_end_time' => '00:09', 'default_end_no' => 'CT09A', 'default_end_depot' => 'KTW4', 'default_special_instructions' => '1178 Last Train from RST3 to KTW4', 'default_row_theme' => null],
            'T13' => ['default_berth_no' => 'CT01B', 'default_outbound_run_no' => '5013', 'default_first_contact_plan' => '04:00', 'default_departure_plan_time' => null, 'default_ktw_platform' => null, 'default_ktw_next_depart_time' => null, 'default_inbound_run_no' => null, 'default_end_station' => null, 'default_end_time' => '0:00', 'default_end_no' => 'CT01B', 'default_end_depot' => 'Standby 6 cars', 'default_row_theme' => 'yellow'],
            'T14' => ['default_berth_no' => 'CT03B', 'default_outbound_run_no' => '1019', 'default_first_contact_plan' => '05:40', 'default_departure_plan_time' => '06:00', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '06:30', 'default_inbound_run_no' => '1054', 'default_end_station' => 'KTW4', 'default_end_time' => '10:14', 'default_end_no' => 'CT03B', 'default_end_depot' => 'Peak time', 'default_special_instructions' => '(Peak time) 1054 Last train NL *** 6 Cars', 'default_row_theme' => 'blue'],
            'T15' => ['default_berth_no' => 'RST2', 'default_outbound_run_no' => '1002', 'default_first_contact_plan' => '04:20', 'default_departure_plan_time' => '04:50', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '05:15', 'default_inbound_run_no' => '1183', 'default_end_station' => 'RST2', 'default_end_time' => '00:23', 'default_end_no' => 'RST3', 'default_end_depot' => 'RST3', 'default_special_instructions' => 'inspection DN to KTW4 // 1183 Last Train from KTW3 to RST2', 'default_row_theme' => 'peach'],
            'T16' => ['default_berth_no' => 'CT10B', 'default_outbound_run_no' => '2005', 'default_first_contact_plan' => '04:05', 'default_departure_plan_time' => '04:35', 'default_ktw_platform' => '9', 'default_ktw_next_depart_time' => '05:00', 'default_inbound_run_no' => '2118', 'default_end_station' => 'KTW9', 'default_end_time' => '00:26', 'default_end_no' => 'CT10B', 'default_end_depot' => 'TLC1', 'default_special_instructions' => '2118 Last train from TLC1 to KTW9', 'default_row_theme' => null],
            'T17' => ['default_berth_no' => 'CT19A', 'default_outbound_run_no' => '5017', 'default_first_contact_plan' => '04:00', 'default_departure_plan_time' => null, 'default_ktw_platform' => null, 'default_ktw_next_depart_time' => null, 'default_inbound_run_no' => null, 'default_end_station' => null, 'default_end_time' => '0:00', 'default_end_no' => 'CT19A', 'default_end_depot' => 'Standby 4 cars', 'default_row_theme' => 'yellow'],
            'T18' => ['default_berth_no' => 'KTW10', 'default_outbound_run_no' => '2003', 'default_first_contact_plan' => '03:45', 'default_departure_plan_time' => '04:15', 'default_ktw_platform' => '9', 'default_ktw_next_depart_time' => '04:40', 'default_inbound_run_no' => '2119', 'default_end_station' => 'TLC1', 'default_end_time' => '00:16', 'default_end_no' => 'CT04A', 'default_end_depot' => 'TLC1', 'default_special_instructions' => '2003 Non stop to TLC1 2119 Last train from KTW9 to TLC1', 'default_row_theme' => null],
            'T19' => ['default_berth_no' => 'CT17A', 'default_outbound_run_no' => '1011', 'default_first_contact_plan' => '04:35', 'default_departure_plan_time' => '05:05', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '05:30', 'default_inbound_run_no' => '1180', 'default_end_station' => 'KTW4', 'default_end_time' => '00:24', 'default_end_no' => 'CT17A', 'default_end_depot' => 'RST3', 'default_special_instructions' => '*** 4 Cars // 1180 Last train NL from RST3 to KTW4', 'default_row_theme' => null],
            'T20' => ['default_berth_no' => 'CT16A', 'default_outbound_run_no' => '5020', 'default_first_contact_plan' => '04:00', 'default_departure_plan_time' => null, 'default_ktw_platform' => null, 'default_ktw_next_depart_time' => null, 'default_inbound_run_no' => null, 'default_end_station' => null, 'default_end_time' => '0:00', 'default_end_no' => 'CT16A', 'default_end_depot' => 'Standby 4 cars', 'default_row_theme' => 'yellow'],
            'T21' => ['default_berth_no' => 'CT17A', 'default_outbound_run_no' => '1011', 'default_first_contact_plan' => '04:35', 'default_departure_plan_time' => '05:05', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '05:30', 'default_inbound_run_no' => '1180', 'default_end_station' => 'KTW4', 'default_end_time' => '00:24', 'default_end_no' => 'CT17A', 'default_end_depot' => 'KTW4', 'default_special_instructions' => '*** 4 Cars // 1180 Last train NL from RST3 to KTW4', 'default_row_theme' => null],
            'T22' => ['default_berth_no' => 'CT13B', 'default_outbound_run_no' => '1301', 'default_first_contact_plan' => '14:05', 'default_departure_plan_time' => '14:35', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '14:55', 'default_inbound_run_no' => '1302', 'default_end_station' => 'KTW4', 'default_end_time' => '00:13', 'default_end_no' => 'CT13B', 'default_end_depot' => 'MW01', 'default_special_instructions' => '1301 KTW3 Non Stop to DMG1 / Standby @ DMG1 / 1302 Non Stop to KTW4', 'default_row_theme' => null],
            'T23' => ['default_berth_no' => 'CT15A', 'default_outbound_run_no' => '5023', 'default_first_contact_plan' => '04:00', 'default_departure_plan_time' => null, 'default_ktw_platform' => null, 'default_ktw_next_depart_time' => null, 'default_inbound_run_no' => null, 'default_end_station' => null, 'default_end_time' => '0:00', 'default_end_no' => 'CT15A', 'default_end_depot' => 'Standby 4 cars', 'default_row_theme' => 'yellow'],
            'T24' => ['default_berth_no' => 'CT07B', 'default_outbound_run_no' => '1021', 'default_first_contact_plan' => '05:50', 'default_departure_plan_time' => '06:10', 'default_ktw_platform' => '3', 'default_ktw_next_depart_time' => '06:40', 'default_inbound_run_no' => '1056', 'default_end_station' => 'KTW4', 'default_end_time' => '10:24', 'default_end_no' => 'TWP, CT04B', 'default_end_depot' => 'Peak time', 'default_special_instructions' => '(Peak time) 1056 Last train NL *** 6 Cars', 'default_row_theme' => 'blue'],
            'T25' => ['default_berth_no' => 'CT17B', 'default_outbound_run_no' => '5025', 'default_first_contact_plan' => '04:00', 'default_departure_plan_time' => null, 'default_ktw_platform' => null, 'default_ktw_next_depart_time' => null, 'default_inbound_run_no' => null, 'default_end_station' => null, 'default_end_time' => '0:00', 'default_end_no' => 'CT17B', 'default_end_depot' => 'Standby 4 cars', 'default_row_theme' => 'yellow'],
        ];

        for ($i = 1; $i <= 25; $i++) {
            $code = 'T' . str_pad((string) $i, 2, '0', STR_PAD_LEFT);

            TrainSet::updateOrCreate(
                ['code' => $code],
                array_merge([
                    'default_consist_type' => in_array($code, $fourCarSets, true) ? '4' : '6',
                    'display_order' => $i,
                    'default_special_instructions' => null,
                    'default_row_theme' => null,
                ], $defaults[$code] ?? [])
            );
        }
    }
}